name: Release

on:
  push:
    tags: ["*"]

jobs:
  publish-cli:
    name: Publish CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-java@v4
        name: Setup Java  
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"

      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.10"

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 8

      - name: Setup Antlr4
        run: pip install --no-input antlr4-tools

      - name: Setup environment
        run: |
            cd packages/cli
            pnpm install

      - name: Publish package
        run: |
            cd packages/cli
            pnpm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
